#!/bin/sh

set -e

if test "$(id -u)" -ne 0; then
  echo "This option must be run as root"
  exit 1
fi

SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR" || exit
SCRIPT_DIR="$(pwd)"

mkdir -p /usr/local/stow/osgit

cp -r "$SCRIPT_DIR"/src/* /usr/local/stow/osgit 
cd /usr/local/stow
stow osgit

original="$(sha256sum "$SCRIPT_DIR"/src/bin/osgit | head -c 64)"

executable_path="/usr/local/bin/osgit"
installed="$(sha256sum "$executable_path" | head -c 64)"

if test "$original" = "$installed"; then
  echo 'Installed correctly.'
else
  echo 'Checksums of your installed file and this version do not match.'
fi

echo
echo "Tip: If you want to uninstall osgit, just 'rm -rf /usr/local/stow/osgit'"
